Revert "Add .random to every ar-class, rather than adding it every time we need it"
This reverts commit 0f8733782058de21aacd830a84696eba9da1dd03.  It was giving us: NoMethodError: undefined method `call' for nil:NilClass in /gems/activerecord-2.3.8/lib/active_record/named_scope.rb:97